- hosts:  '{{ hosts }}'
  remote_user: ec2-user
  sudo: yes
  tasks:
    - name: ensure /home/www/publish-shell
      file: path=/home/www/publish-shell owner=ec2-user group=ec2-user state=directory mode=0755

    - name: sync publish-shell
      synchronize: src=/home/www/publish-shell/server-shell/ dest=/home/www/publish-shell/

    - name: chown ec2-user:ec2-user -R /home/www/publish-shell
      shell: chown ec2-user:ec2-user -R /home/www/publish-shell
