- hosts:  '{{ hosts }}'
  remote_user: ec2-user
  sudo: yes
  tasks:
    - name: yum libpcap libpcap-devel ncurses ncurses-devel
      shell: yum -y install  libpcap libpcap-devel ncurses ncurses-devel

    - name: yum flex byacc
      shell: yum -y install flex byacc 

    - name: copy iftop-1.0pre4.tar.gz
      copy: src=/usr/local/src/iftop-1.0pre4.tar.gz  dest=/tmp

    - name: install iftop-1.0pre4.tar.gz
      shell: tar -xzvf /tmp/iftop-1.0pre4.tar.gz -C /tmp/;
             cd /tmp/iftop-1.0pre4;
             ./configure;
             make && make install;
             ln -s /usr/local/sbin/iftop /usr/bin/iftop

