- hosts:  '{{ hosts }}'
  remote_user: ec2-user
  sudo: yes
  tasks:
    - name: sync {{user}} hosts
      copy: src=/home/www/ansible/files/{{localdir}}/hosts dest=/etc/hosts

    - name: sync {{user}} profile
      copy: src=/home/www/ansible/files/{{localdir}}/profile dest=/etc/profile

