- hosts:  '{{ hosts }}'
  remote_user: ec2-user
  sudo: yes
  tasks:
    - name: sync .keystore
      copy: src=/home/www/ansible/files/common/.keystore dest=/home/ec2-user/

    - name: create /data/logs
      file: path=/data/logs owner=ec2-user group=ec2-user state=directory mode=0755

    - name: sync env.sh 
      copy: src=/home/www/ansible/files/{{type}}/env.sh dest=/etc/profile.d/

    - name: sync jdk1.8.0_60
      synchronize: src=/home/www/ansible/files/java/jdk1.8.0_60 dest=/usr/java/

    - name: rm /usr/bin/java
      shell: rm /usr/bin/java

    - name: ln -s /usr/java/jdk1.8.0_60/bin/java /usr/bin/java
      shell: ln -s /usr/java/jdk1.8.0_60/bin/java /usr/bin/java

    - name: create /data/tomcat
      file: path=/data/tomcat owner=ec2-user group=ec2-user state=directory mode=0755

