#- hosts:  '{{ hosts }}'
- hosts:  new-server
  remote_user: ec2-user
  sudo: yes
  tasks:
    - name: yum gcc
      yum: pkg=gcc state=latest

    - name: yum openssl
      yum: pkg=openssl state=latest

    - name: yum openssl-devel
      yum: pkg=openssl-devel state=latest

    - name: yum pcre-devel
      yum: pkg=pcre-devel state=latest

    - name: copy nginx.tar.gz
      copy: src=/usr/local/src/nginx-1.10.1.tar.gz  dest=/tmp/
   
    - name: install nginx
      shell: tar -xzvf /tmp/nginx-1.10.1.tar.gz -C /tmp/;
             cd /tmp/nginx-1.10.1; 
             ./configure --prefix=/usr/local/nginx --sbin-path=/usr/local/nginx/sbin/nginx --conf-path=/etc/nginx/nginx.conf --error-log-path=/data/logs/nginx/error.log --http-log-path=/data/logs/nginx/access.log --pid-path=/var/run/nginx.pid --with-http_ssl_module --with-http_realip_module --with-http_addition_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gzip_static_module --with-http_random_index_module --with-http_secure_link_module --with-http_stub_status_module --with-mail --with-mail_ssl_module --with-file-aio;
             make &&  make install

    - name: nginx.conf
      template: src=/home/www/ansible/templates/nginx.conf dest=/etc/nginx/nginx.conf mode=644 owner=ec2-user group=ec2-user
    
    - name: mkdir /data/nginx/
      file: path=/data/nginx/ state=directory owner=ec2-user group=ec2-user

#    - name: start nginx
#      shell: /usr/local/nginx/sbin/nginx -c /etc/nginx/nginx.conf
